import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, Grid, IconButton, InputLabel, MenuItem, Select, Stack, TextField, Tooltip, Typography } from '@mui/material';
import { Eye, Pencil, Play, Plus, Search, Star, Trash2, X, Send, Undo2 } from 'lucide-react';
import { motion } from 'framer-motion';

const MotionDiv = motion.create('div');
import { videosApi } from '../../services/backend';
import { GlassCard } from '../../components/ui/GlassCard';
import { SectionHeader } from '../../components/ui/SectionHeader';
import type { Video } from '../../types/api';

type VideoForm = { title: string; description: string; videoUrl: string; thumbnailUrl: string; category: string };
const emptyForm: VideoForm = { title: '', description: '', videoUrl: '', thumbnailUrl: '', category: 'Career Stories' };

export function VideosPage() {
  const qc = useQueryClient(); const [search, setSearch] = useState(''); const [published, setPublished] = useState<'all' | 'true' | 'false'>('all'); const [featured, setFeatured] = useState<'all' | 'true' | 'false'>('all'); const [category, setCategory] = useState('all'); const [editing, setEditing] = useState<Video | null>(null); const [preview, setPreview] = useState<Video | null>(null); const [creating, setCreating] = useState(false); const [form, setForm] = useState(emptyForm); const [error, setError] = useState<string | null>(null);
  const query = useQuery({ queryKey: ['videos', search, published, featured, category], queryFn: () => videosApi.list({ title: search || undefined, published: published === 'all' ? undefined : published === 'true', featured: featured === 'all' ? undefined : featured === 'true', category: category === 'all' ? undefined : category, size: 20, sort: 'createdAt,desc' }) });
  const categories = useMemo(() => Array.from(new Set((query.data?.content ?? []).map((item) => item.category))).sort(), [query.data]);
  const save = useMutation({ mutationFn: async () => { const payload = { title: form.title.trim(), description: form.description.trim(), videoUrl: form.videoUrl.trim(), thumbnailUrl: form.thumbnailUrl.trim() || undefined, category: form.category.trim() }; return editing ? videosApi.update(editing.id, payload) : videosApi.create(payload); }, onSuccess: () => { void qc.invalidateQueries({ queryKey: ['videos'] }); setCreating(false); setEditing(null); setForm(emptyForm); setError(null); }, onError: (e: Error) => setError(e.message) });
  const action = useMutation({ mutationFn: async ({ id, type }: { id: number; type: 'publish' | 'unpublish' | 'feature' | 'unfeature' | 'delete' }) => { if (type === 'publish') return videosApi.publish(id); if (type === 'unpublish') return videosApi.unpublish(id); if (type === 'feature') return videosApi.feature(id); if (type === 'unfeature') return videosApi.unfeature(id); return videosApi.remove(id); }, onSuccess: () => { void qc.invalidateQueries({ queryKey: ['videos'] }); } });
  const openEdit = (video: Video) => { setEditing(video); setForm({ title: video.title, description: video.description, videoUrl: video.videoUrl, thumbnailUrl: video.thumbnailUrl ?? '', category: video.category }); setCreating(true); setError(null); };
  return <Stack gap={3}><SectionHeader eyebrow="MEDIA STUDIO" title="Videos" description="Manage candidate-facing video stories, resources and featured media." action={<Button variant="contained" startIcon={<Plus size={17} />} onClick={() => { setEditing(null); setForm(emptyForm); setCreating(true); setError(null); }}>New video</Button>} />
    <GlassCard sx={{ p: 2 }}><Grid container spacing={1.5}><Grid size={{ xs: 12, md: 4 }}><TextField fullWidth size="small" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search videos…" slotProps={{ input: { startAdornment: <Search size={16} style={{ marginRight: 8 }} /> } }} /></Grid><Grid size={{ xs: 4, md: 2.5 }}><FormControl fullWidth size="small"><InputLabel>Publication</InputLabel><Select label="Publication" value={published} onChange={(e) => setPublished(e.target.value as typeof published)}><MenuItem value="all">All</MenuItem><MenuItem value="true">Published</MenuItem><MenuItem value="false">Drafts</MenuItem></Select></FormControl></Grid><Grid size={{ xs: 4, md: 2.5 }}><FormControl fullWidth size="small"><InputLabel>Featured</InputLabel><Select label="Featured" value={featured} onChange={(e) => setFeatured(e.target.value as typeof featured)}><MenuItem value="all">All</MenuItem><MenuItem value="true">Featured</MenuItem><MenuItem value="false">Standard</MenuItem></Select></FormControl></Grid><Grid size={{ xs: 4, md: 3 }}><FormControl fullWidth size="small"><InputLabel>Category</InputLabel><Select label="Category" value={category} onChange={(e) => setCategory(e.target.value)}><MenuItem value="all">All categories</MenuItem>{categories.map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</Select></FormControl></Grid></Grid></GlassCard>
    {query.isError && <Alert severity="error">Unable to load videos. {query.error instanceof Error ? query.error.message : 'Please try again.'}</Alert>}
    <Grid container spacing={2}>{(query.data?.content ?? []).map((video, index) => <Grid key={video.id} size={{ xs: 12, md: 6, xl: 4 }}><MotionDiv initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .04 }} style={{ height: '100%' }}><GlassCard sx={{ height: '100%', overflow: 'hidden', p: 0, '&:hover': { borderColor: 'primary.main' } }}>{video.thumbnailUrl ? <Box component="img" src={video.thumbnailUrl} alt="" sx={{ width: '100%', height: 190, objectFit: 'cover', display: 'block' }} /> : <Box sx={{ height: 190, display: 'grid', placeItems: 'center', background: 'linear-gradient(135deg, rgba(16,42,67,.18), rgba(200,155,60,.10))' }}><Play size={38} /></Box>}<Stack gap={1.5} sx={{ p: 2 }}><Stack direction="row" gap={1} flexWrap="wrap"><Chip size="small" label={video.category} /><Chip size="small" label={video.published ? 'Published' : 'Draft'} color={video.published ? 'success' : 'default'} />{video.featured && <Chip size="small" icon={<Star size={13} />} label="Featured" color="warning" />}</Stack><Typography fontWeight={850}>{video.title}</Typography><Typography variant="body2" color="text.secondary" sx={{ minHeight: 40 }}>{video.description || 'No description provided.'}</Typography><Stack direction="row" justifyContent="flex-end" gap={.4}><Tooltip title="Preview"><IconButton onClick={() => setPreview(video)}><Eye size={18} /></IconButton></Tooltip><Tooltip title="Edit"><IconButton onClick={() => openEdit(video)}><Pencil size={18} /></IconButton></Tooltip>{video.published ? <Tooltip title="Unpublish"><IconButton onClick={() => action.mutate({ id: video.id, type: 'unpublish' })}><Undo2 size={18} /></IconButton></Tooltip> : <Tooltip title="Publish"><IconButton color="primary" onClick={() => action.mutate({ id: video.id, type: 'publish' })}><Send size={18} /></IconButton></Tooltip>}{video.featured ? <Tooltip title="Remove featured"><IconButton color="warning" onClick={() => action.mutate({ id: video.id, type: 'unfeature' })}><Star size={18} /></IconButton></Tooltip> : <Tooltip title="Feature"><IconButton onClick={() => action.mutate({ id: video.id, type: 'feature' })}><Star size={18} /></IconButton></Tooltip>}<Tooltip title="Delete"><IconButton color="error" onClick={() => { if (window.confirm(`Delete “${video.title}”?`)) action.mutate({ id: video.id, type: 'delete' }); }}><Trash2 size={18} /></IconButton></Tooltip></Stack></Stack></GlassCard></MotionDiv></Grid>)}</Grid>
    <Dialog open={creating} onClose={() => !save.isPending && setCreating(false)} fullWidth maxWidth="md"><DialogTitle>{editing ? 'Edit video' : 'Create video'}<IconButton onClick={() => setCreating(false)} sx={{ position: 'absolute', right: 10, top: 10 }}><X size={18} /></IconButton></DialogTitle><DialogContent dividers><Stack gap={2} sx={{ pt: 1 }}><TextField label="Title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /><Grid container spacing={2}><Grid size={{ xs: 12, md: 6 }}><TextField fullWidth label="Category" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} required /></Grid><Grid size={{ xs: 12, md: 6 }}><TextField fullWidth label="Video URL" value={form.videoUrl} onChange={(e) => setForm({ ...form, videoUrl: e.target.value })} required /></Grid><Grid size={{ xs: 12 }}><TextField fullWidth label="Thumbnail URL" value={form.thumbnailUrl} onChange={(e) => setForm({ ...form, thumbnailUrl: e.target.value })} /></Grid></Grid><TextField label="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} multiline minRows={5} />{error && <Alert severity="error">{error}</Alert>}</Stack></DialogContent><DialogActions sx={{ p: 2 }}><Button variant="outlined" onClick={() => setCreating(false)}>Cancel</Button><Button variant="contained" onClick={() => save.mutate()} disabled={save.isPending || !form.title.trim() || !form.videoUrl.trim() || !form.category.trim()}>{save.isPending ? 'Saving…' : editing ? 'Save changes' : 'Create video'}</Button></DialogActions></Dialog>
    <Dialog open={Boolean(preview)} onClose={() => setPreview(null)} fullWidth maxWidth="md"><DialogTitle>{preview?.title}<IconButton onClick={() => setPreview(null)} sx={{ position: 'absolute', right: 10, top: 10 }}><X size={18} /></IconButton></DialogTitle><DialogContent dividers>{preview && <Stack gap={2}>{preview.thumbnailUrl && <Box component="img" src={preview.thumbnailUrl} alt="" sx={{ width: '100%', maxHeight: 340, objectFit: 'cover', borderRadius: 2 }} />}<Box component="video" src={preview.videoUrl} controls sx={{ width: '100%', maxHeight: 420, borderRadius: 2, bgcolor: 'common.black' }} /><Typography color="text.secondary">{preview.description}</Typography></Stack>}</DialogContent></Dialog>
  </Stack>;
}
