import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, FormControl, Grid, IconButton, InputLabel, MenuItem, Select, Stack, TextField, Tooltip, Typography } from '@mui/material';
import { FileText, Eye, Pencil, Plus, Trash2, X, Send, Undo2, Search } from 'lucide-react';
import { motion } from 'framer-motion';

const MotionDiv = motion.create('div');
import { articlesApi } from '../../services/backend';
import { GlassCard } from '../../components/ui/GlassCard';
import { SectionHeader } from '../../components/ui/SectionHeader';
import type { Article } from '../../types/api';

type ArticleForm = { title: string; excerpt: string; content: string; category: string; featuredImage: string };
const emptyForm: ArticleForm = { title: '', excerpt: '', content: '', category: 'Career Advice', featuredImage: '' };

function slugPreview(title: string) { return title.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'article-slug'; }
function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' }).format(new Date(value)) : '—'; }

export function ArticlesPage() {
  const qc = useQueryClient();
  const [search, setSearch] = useState('');
  const [published, setPublished] = useState<'all' | 'true' | 'false'>('all');
  const [category, setCategory] = useState('all');
  const [editing, setEditing] = useState<Article | null>(null);
  const [preview, setPreview] = useState<Article | null>(null);
  const [creating, setCreating] = useState(false);
  const [form, setForm] = useState<ArticleForm>(emptyForm);
  const [error, setError] = useState<string | null>(null);

  const query = useQuery({ queryKey: ['articles', search, published, category], queryFn: () => articlesApi.list({ title: search || undefined, published: published === 'all' ? undefined : published === 'true', category: category === 'all' ? undefined : category, size: 20, sort: 'createdAt,desc' }) });
  const categories = useMemo(() => Array.from(new Set((query.data?.content ?? []).map((item) => item.category))).sort(), [query.data]);
  const mutation = useMutation({ mutationFn: async () => { const payload = { title: form.title.trim(), excerpt: form.excerpt.trim(), content: form.content.trim(), category: form.category.trim(), featuredImage: form.featuredImage.trim() || undefined }; return editing ? articlesApi.update(editing.id, payload) : articlesApi.create(payload); }, onSuccess: () => { void qc.invalidateQueries({ queryKey: ['articles'] }); setCreating(false); setEditing(null); setForm(emptyForm); setError(null); }, onError: (e: Error) => setError(e.message) });
  const action = useMutation({ mutationFn: async ({ id, type }: { id: number; type: 'publish' | 'unpublish' | 'delete' }) => type === 'publish' ? articlesApi.publish(id) : type === 'unpublish' ? articlesApi.unpublish(id) : articlesApi.remove(id), onSuccess: () => { void qc.invalidateQueries({ queryKey: ['articles'] }); } });

  const openCreate = () => { setEditing(null); setForm(emptyForm); setCreating(true); setError(null); };
  const openEdit = (article: Article) => { setEditing(article); setForm({ title: article.title, excerpt: article.excerpt, content: article.content, category: article.category, featuredImage: article.featuredImage ?? '' }); setCreating(true); setError(null); };
  const saveDisabled = !form.title.trim() || !form.content.trim() || !form.category.trim() || mutation.isPending;

  return <Stack gap={3}>
    <SectionHeader eyebrow="CONTENT STUDIO" title="Articles" description="Create, refine and publish candidate-facing guidance without leaving the enterprise workspace." action={<Button variant="contained" startIcon={<Plus size={17} />} onClick={openCreate}>New article</Button>} />
    <GlassCard sx={{ p: 2 }}><Grid container spacing={1.5} alignItems="center"><Grid size={{ xs: 12, md: 5 }}><TextField fullWidth size="small" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search articles…" slotProps={{ input: { startAdornment: <Search size={16} style={{ marginRight: 8 }} /> } }} /></Grid><Grid size={{ xs: 6, md: 3 }}><FormControl fullWidth size="small"><InputLabel>Publication</InputLabel><Select label="Publication" value={published} onChange={(e) => setPublished(e.target.value as typeof published)}><MenuItem value="all">All</MenuItem><MenuItem value="true">Published</MenuItem><MenuItem value="false">Drafts</MenuItem></Select></FormControl></Grid><Grid size={{ xs: 6, md: 3 }}><FormControl fullWidth size="small"><InputLabel>Category</InputLabel><Select label="Category" value={category} onChange={(e) => setCategory(e.target.value)}><MenuItem value="all">All categories</MenuItem>{categories.map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</Select></FormControl></Grid><Grid size={{ xs: 12, md: 1 }}><Typography variant="caption" color="text.secondary">{query.data?.totalElements ?? 0} total</Typography></Grid></Grid></GlassCard>
    {query.isError && <Alert severity="error">Unable to load articles. {query.error instanceof Error ? query.error.message : 'Please try again.'}</Alert>}
    <Stack gap={1.25}>{(query.data?.content ?? []).map((article, index) => <MotionDiv key={article.id} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .035 }}><GlassCard sx={{ p: 2, '&:hover': { borderColor: 'primary.main' } }}><Stack direction={{ xs: 'column', md: 'row' }} gap={2} alignItems={{ md: 'center' }}><Box sx={{ width: 58, height: 58, borderRadius: 2.5, display: 'grid', placeItems: 'center', bgcolor: 'action.hover', color: 'primary.main', flexShrink: 0 }}><FileText size={24} /></Box><Box sx={{ flex: 1, minWidth: 0 }}><Typography fontWeight={850} noWrap>{article.title}</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .35 }}>{article.category} · Updated {formatDate(article.updatedAt)}</Typography><Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: .6 }}>{article.excerpt || 'No excerpt provided.'}</Typography></Box><Stack direction="row" gap={1} alignItems="center"><Chip size="small" label={article.published ? 'Published' : 'Draft'} color={article.published ? 'success' : 'default'} /><Tooltip title="Preview"><IconButton onClick={() => setPreview(article)}><Eye size={18} /></IconButton></Tooltip><Tooltip title="Edit"><IconButton onClick={() => openEdit(article)}><Pencil size={18} /></IconButton></Tooltip>{article.published ? <Tooltip title="Unpublish"><IconButton onClick={() => action.mutate({ id: article.id, type: 'unpublish' })}><Undo2 size={18} /></IconButton></Tooltip> : <Tooltip title="Publish"><IconButton color="primary" onClick={() => action.mutate({ id: article.id, type: 'publish' })}><Send size={18} /></IconButton></Tooltip>}<Tooltip title="Delete"><IconButton color="error" onClick={() => { if (window.confirm(`Delete “${article.title}”?`)) action.mutate({ id: article.id, type: 'delete' }); }}><Trash2 size={18} /></IconButton></Tooltip></Stack></Stack></GlassCard></MotionDiv>)}</Stack>
    {!query.isLoading && !query.data?.content.length && <GlassCard sx={{ p: 6, textAlign: 'center' }}><Typography variant="h6" fontWeight={800}>No articles found</Typography><Typography color="text.secondary" sx={{ mt: .5 }}>Try a different filter or create your first article.</Typography></GlassCard>}

    <Dialog open={creating} onClose={() => !mutation.isPending && setCreating(false)} fullWidth maxWidth="md"><DialogTitle>{editing ? 'Edit article' : 'Create article'}<IconButton onClick={() => setCreating(false)} sx={{ position: 'absolute', right: 10, top: 10 }}><X size={18} /></IconButton></DialogTitle><DialogContent dividers><Stack gap={2} sx={{ pt: 1 }}><TextField label="Title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /><Typography variant="caption" color="text.secondary">Public slug preview: /articles/{slugPreview(form.title)}</Typography><Grid container spacing={2}><Grid size={{ xs: 12, md: 7 }}><TextField fullWidth label="Category" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} required /></Grid><Grid size={{ xs: 12, md: 5 }}><TextField fullWidth label="Featured image URL" value={form.featuredImage} onChange={(e) => setForm({ ...form, featuredImage: e.target.value })} /></Grid></Grid><TextField label="Excerpt" value={form.excerpt} onChange={(e) => setForm({ ...form, excerpt: e.target.value })} multiline minRows={2} /><TextField label="Content" value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} multiline minRows={12} required helperText="Keep content readable and candidate-focused. Rich HTML is not required by the current backend contract." />{error && <Alert severity="error">{error}</Alert>}</Stack></DialogContent><DialogActions sx={{ p: 2 }}><Button variant="outlined" onClick={() => setCreating(false)}>Cancel</Button><Button variant="contained" onClick={() => mutation.mutate()} disabled={saveDisabled}>{mutation.isPending ? 'Saving…' : editing ? 'Save changes' : 'Create article'}</Button></DialogActions></Dialog>
    <Dialog open={Boolean(preview)} onClose={() => setPreview(null)} fullWidth maxWidth="md"><DialogTitle>{preview?.title}<IconButton onClick={() => setPreview(null)} sx={{ position: 'absolute', right: 10, top: 10 }}><X size={18} /></IconButton></DialogTitle><DialogContent dividers>{preview && <Stack gap={2}><Stack direction="row" gap={1} alignItems="center"><Chip size="small" label={preview.category} /><Typography variant="caption" color="text.secondary">{preview.published ? `Published ${formatDate(preview.publishedAt)}` : 'Draft'}</Typography></Stack><Typography variant="h6" fontWeight={800}>{preview.excerpt}</Typography><Divider />{preview.featuredImage && <Box component="img" src={preview.featuredImage} alt="" sx={{ width: '100%', maxHeight: 300, objectFit: 'cover', borderRadius: 2 }} />}{preview.content.split(/\n+/).map((paragraph, index) => <Typography key={index} color="text.secondary" sx={{ lineHeight: 1.8 }}>{paragraph}</Typography>)}</Stack>}</DialogContent></Dialog>
  </Stack>;
}
